### ISSUE TITLE
Try compatibility with xbar (reboot of swiftbar)

### ISSUE THREAD

**Issue by matopeto** [matopeto/xcode-build-times#16]
swiftbar is now xbar, it reboot from @matryer https://github.com/matryer/xbar/ try if this plugin is fully compatible with new binary

**Comment by salimos** [comment]
It is, just need to update the Xcode > Preferences > Behaviors to the new default plugin directory : 
~/Library/Application Support/xbar/plugins

Just the readme file the app name should be changed from bitbar to xbar (the link redirect automatically)

**Comment by matopeto** [comment]
@salimos thank you for testing. I will prepare PR with updated readme and will test it again myself when i will have more time. Now i use swiftbar on my work computer.

**Comment by matopeto** [comment]
Seems OK, closing
