### ISSUE TITLE
Monterey issues: Xcode error "Failed to launch script .... No such file or directory" or "php: bad interpreter" or "env: php: No such file or directory"

### ISSUE THREAD

**Issue by matopeto** [matopeto/xcode-build-times#17]
I create this issue because in macOS Monterey there is no PHP that can run this script.

If you have this problem and you want to use this plugin on Monterey you must 

1. install PHP

E.g. from Hombrew

```
brew install php
```

2. Update/download the plugin to the latests version

If you are using https://github.com/swiftbar/SwiftBar and you are getting 

> env: php: No such file or directory

It is because `$PATH` is not correct for the plugin.

If your default shell is `Zsh` just go to Swiftbar Settings and switch Shell to the "Zsh"

⚠️ but there is another bug that xcode cannot run hombrew PHP (yet), it don't see homebrew bin folder in the PATH
If it is your problem you must now after plugin download change first line of plugin 

from:

`#!/usr/bin/env php` or `#!/usr/bin/php`

to path where PHP is actually stored (you can determine it by run the command `which php`

`#!/opt/homebrew/bin/php`

I will resolve this issue later. Sorry for inconvenience.

---

If you don't want use this plugin anymore, just disable it in SwiftBar/Bitbar in settings, Remove from plugin directory and remove from Xcode Behaviours 

Xcode -> Preferences -> Behaviors, and uncheck "Run" at the end of all the phases (oposite as is in the readme)

I maybe rewrite this plugin from PHP to other language, but maybe not. See #12 for updates :)

**Comment by ajmaurya99** [comment]
macOS 12 (Monterey) removes the system provided PHP and you will need to install it yourself.

It is easy to install if you have brew installed. Simply run the following:

`brew install php@7.4 brew-php-switcher`

This will install the latest version of PHP 7.4 as well as a handy utility for switching between PHP versions if you need to.

Also try running -` brew link php@7.4`

**Comment by matopeto** [comment]
@ajmaurya99 yes. The issue is about it :) also the solution :) problem is the path to the php excecutable, and i cannot create univeral solution to old (system) PHP and new homebrew PHP. 

So for now you have to also manualy change first line of the plugin to match your actual full path to PHP executable :)

but maybe i create two version of the plugin :)

**Comment by matopeto** [comment]
I added 'configure' command to the plugin and update README so i can close the issue now.
