### ISSUE TITLE
Xcode not calling script

### ISSUE THREAD

**Issue by derrickshowers** [matopeto/xcode-build-times#20]
Hi @matopeto I'm having issues getting this working (had it working on a previous machine). I've narrowed it down to an issue with Xcode running the script. If I call it myself in terminal (`php xcodeBuildTimes.1m.php start` and `php xcodeBuildTimes.1m.php success`) it works (and records an entry in the .csv), but when I build via Xcode it's not getting executed for some reason. Here's a screenshot of my Xcode prefs which clearly shows it's there. Is there any additional debugging or logging I can do to figure out what's going on? Any recent issues you're aware of? Thank you! 🙏 

<img width="200" alt="Screen Shot 2022-03-17 at 12 00 52 PM" src="https://user-images.githubusercontent.com/1372292/158842374-c1f3d55a-3740-4a6d-ad3e-fb896d53af4d.png">

**Comment by matopeto** [comment]
Hi, This is becasue Xcode doesn't see PHP in the path. See: #17 you have to determine full path to your PHP by running `which php` and update first line to the php executable

e.g. to `#!/opt/homebrew/bin/php` (if you are on Apple silicone and you install PHP with homebrew)

**Comment by derrickshowers** [comment]
Yup that was it. Thanks so much for the quick response. Sorry, I read that thread, but didn't realize it was the same issue. Thanks so much!!
