### ISSUE TITLE
Wrong data when two Project builds are overlapping

### ISSUE THREAD

**Issue by igorkulman** [matopeto/xcode-build-times#5]
I started building Project 1 and while the build was in progress I started building Project 2. The result was a broken entry with wrong duration

```csv
"2020-04-28 14:11:08",1588083068,success,,itlwm.xcodepro
```
skewing the total and average build times quite significantly 

<img width="450" alt="Screenshot 2020-04-28 at 18 03 32" src="https://user-images.githubusercontent.com/4746070/80511003-cf4af400-897b-11ea-9c2b-0d7b019d9636.png">

**Comment by matopeto** [comment]
I cannot reproduce. But i will add checks if start time is correctly written.

**Comment by matopeto** [comment]
Added support for paralel builds (Start file contains hash of workspace or project directory)
