### ISSUE TITLE
Handle local timezone

### ISSUE THREAD

**Issue by matopeto** [matopeto/xcode-build-times#8]
Now in data file is written only time without timezone (in UTC?) and duration. And we compute and show statisticts in default php timezone)  So today's statistics is not always correct. For correct today's statistics use system timezone for compute and show statistics.

**Comment by matopeto** [comment]
To get system timezone from php, run: 

`/bin/ls -l /etc/localtime | /usr/bin/cut -d '/' -f 8,9`

More info: https://stackoverflow.com/a/32604655

**Comment by derrickshowers** [comment]
+1 to this! Was going to open an issue for the same thing. I was wondering why my build time was so low last night.

(Plugin in great btw!)

**Comment by matopeto** [comment]
Resolved. You can update with "About -> Update" directly from the plugin
